# Generated by Django 5.1.4 on 2024-12-31 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='empleados',
            field=models.ManyToManyField(limit_choices_to={'rol': 'empleado'}, related_name='proyectos_asignados', to='gestion.usuario'),
        ),
    ]
