# Generated by Django 5.1.4 on 2025-01-21 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_usuario_encargado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['-created_at']},
        ),
    ]
